
# Nome da pipeline
name: "Pipeline de Conclusao do Curso"

# Gatilhos de disparo ajustados corretamente
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Executa todo domingo à meia-noite (UTC)

# Tarefas dentro da pipeline
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Baixa o código para dentro da máquina virtual
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # 2. Instala e configura o ambiente do Node.js
      - name: Configuração do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # 3. Instala as dependências (incluindo mocha e mochawesome)
      - name: Instalar Dependências
        run: npm ci

      # 4. Executa os testes 
      - name: Executando testes com Mochawesome
        run: npm run test:report
        if: always()

      # 5. Salva o HTML do Mochawesome
      - name: Salvar Relatório HTML do Mochawesome
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorio-mochawesome
          path: mochawesome-report/
          retention-days: 7

      # 6. Publica a pasta do relatório na internet
      - name: Publicar Relatório Online no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: always() # Garante que atualiza a página mesmo se o teste falhar
        with:
          folder: mochawesome-report # Pasta que a action vai subir
          branch: gh-pages # Branch onde a página vai morar