# Nome da pipeline
name: Pipeline de Conclusao do Curso

# Gatilhos - Execução por push
on:
  push:
    branches:
      - main

# Manual
  workflow_dispatch:

# Agendado
  schedule:
    - cron: '0 0 * * 0' # Executa todo domingo à meia-noite

#tarefas dentro da pipeline = jobs
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Executando testes com Mochawesome
        run: npm run test:report
        if: always() # Garante que vai rodar mesmo se algum teste falhar

      # Salva o HTML do Mochawesome para você baixar direto pelo painel do GitHub
    - name: Salvar Relatório HTML do Mochawesome
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: relatorio-mochawesome
        path: mochawesome-report/ # Caminho da pasta que configuramos no package.json
        retention-days: 7